- name: start goshimmer
  systemd:
    name: goshimmer.service
    state: started
    daemon_reload: yes
    enabled: yes
  register: goshimmer_started

- name: jq format config
  shell: 'UUID=$(uuidgen); jq . < "{{ goshimmer_home_path }}/config.json" > "/tmp/ansible.format.${UUID}" && mv -- "/tmp/ansible.format.${UUID}" "{{ goshimmer_home_path }}/config.json" && chown {{ goshimmer_user }}:{{ goshimmer_group }} "{{ goshimmer_home_path }}/config.json" && chmod 600 "{{ goshimmer_home_path }}/config.json"'

- name: restart goshimmer
  systemd:
    name: goshimmer.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  when:
    - not skip_goshimmer_restart|default(False)|bool
    - not goshimmer_started.changed|default(False)|bool
