- name: ensure firewalld started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: allow goshimmer tcp port in firewall
  firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items: "{{ goshimmer_ports }}"

- name: allow goshimmer tcp port in firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ goshimmer_external_spammer_port }}/tcp"
    - "{{ goshimmer_external_dashboard_port }}/tcp"
  when: install_nginx | default(true) | bool
